# Generated by Django 3.2.22 on 2023-10-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20231010_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='province',
            field=models.CharField(blank=True, choices=[('KENYA', 'KENYA'), ('UGANDA', 'UGANDA'), ('TANZANIA', 'TANZANIA'), ('RWANDA', 'RWANDA')], max_length=100),
        ),
    ]
