# Generated by Django 3.2.22 on 2023-10-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_alter_client_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('KES', 'KSH'), ('$', 'USD')], default='R', max_length=100),
        ),
        migrations.AlterField(
            model_name='settings',
            name='province',
            field=models.CharField(blank=True, choices=[('KENYA', 'KENYA'), ('UGANDA', 'UGANDA'), ('TANZANIA', 'TANZANIA'), ('RWANDA', 'RWANDA')], max_length=100),
        ),
    ]
