# Generated by Django 3.2.22 on 2023-10-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_auto_20231010_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='paymentTerms',
            field=models.CharField(choices=[('15 days', '15 days'), ('30 days', '30 days'), ('60 days', '60 days'), ('90 days', '90 days'), ('120 days', '120 days'), ('150 days', '150 days'), ('180 days', '180 days')], default='14 days', max_length=100),
        ),
    ]
