# Generated by Django 3.2.22 on 2023-10-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_product_rateperkilo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(choices=[('15 days', '35'), ('30 days', '30 days'), ('60 days', '60 days'), ('90 days', '90 days'), ('120 days', '120 days'), ('150 days', '150 days'), ('180 days', '180 days')], default='14 days', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='rateperkilo',
            field=models.CharField(choices=[('15 days', '35'), ('30 days', '30 days'), ('60 days', '60 days'), ('90 days', '90 days'), ('120 days', '120 days'), ('150 days', '150 days'), ('180 days', '180 days')], default='14 days', max_length=100),
        ),
    ]
