# Generated by Django 3.2.22 on 2023-10-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_alter_settings_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='paymentTerms',
            field=models.CharField(choices=[('15 days', '15 days- price:35'), ('30 days', '30 days- price:40'), ('60 days', '60 days- price:50'), ('90 days', '60 days- price:60'), ('120 days', '60 days- price:70'), ('150 days', '60 days- price:80'), ('180 days', '60 days- price:90')], default='14 days', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='province',
            field=models.CharField(blank=True, choices=[('Nairobi', 'Nairobi'), ('Nakuru', 'Nakuru'), ('Eldoret', 'Eldoret'), ('Kisumu', 'Kisumu')], max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paymentTerms',
            field=models.CharField(choices=[('15 days', '15 days'), ('30 days', '30 days'), ('60 days', '60 days'), ('90 days', '60 days'), ('120 days', '60 days'), ('150 days', '60 days'), ('180 days', '60 days')], default='14 days', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('Kes', 'ksh'), ('$', 'USD')], default='R', max_length=100),
        ),
    ]
