# Generated by Django 3.2.22 on 2023-10-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_auto_20231012_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='paymentTerms',
            field=models.CharField(choices=[('15 days', '15 days'), ('30 days', '30 days'), ('60 days', '60 days'), ('90 days', '90 days'), ('120 days', '120 days'), ('150 days', '150 days'), ('180 days', '180 days')], default='14 days', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='paymentTerms',
            field=models.CharField(choices=[('15 days', '15 days- price:35'), ('30 days', '30 days- price:40'), ('60 days', '60 days- price:50'), ('90 days', '90 days- price:60'), ('120 days', '120 days- price:70'), ('150 days', '150 days- price:80'), ('180 days', '180 days- price:90')], default='14 days', max_length=100),
        ),
    ]
