# Generated by Django 3.2.22 on 2023-10-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0012_auto_20231012_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rates',
            field=models.CharField(choices=[('15', '15 days - $35 per kilo'), ('30', '30 days - $40 per kilo'), ('60', '60 days - $50 per kilo'), ('90', '90 days - $60 per kilo'), ('120', '120 days - $70 per kilo'), ('150', '150 days - $80 per kilo'), ('180', '180 days - $90 per kilo')], default='14 days', max_length=100),
        ),
    ]
