# Generated by Django 3.2.22 on 2023-10-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0013_alter_product_rates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rates',
            field=models.CharField(choices=[('15', '15 days - ksh 35 per kilo'), ('30', '30 days - ksh 40 per kilo'), ('60', '60 days - ksh 50 per kilo'), ('90', '90 days - ksh 60 per kilo'), ('120', '120 days - ksh 70 per kilo'), ('150', '150 days - ksh 80 per kilo'), ('180', '180 days - ksh 90 per kilo')], default='14 days', max_length=100),
        ),
    ]
