# Generated by Django 3.2.22 on 2023-10-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0014_alter_product_rates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rates',
            field=models.CharField(choices=[('35', '15 days - ksh 35 per kilo'), ('40', '30 days - ksh 40 per kilo'), ('50', '60 days - ksh 50 per kilo'), ('60', '90 days - ksh 60 per kilo'), ('70', '120 days - ksh 70 per kilo'), ('80', '150 days - ksh 80 per kilo'), ('90', '180 days - ksh 90 per kilo')], default='14 days', max_length=100),
        ),
    ]
